server:
  port: 8888
  servlet:
    context-path: /web
spring:
  datasource:
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ShareHorizon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  mail:
    host: smtp.qq.com
    username: aaronduz@qq.com
    password: kpirfnaqsfljecii
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8